name: "Run unit tests"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-java:
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["17", "22", "23"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: "${{ matrix.java-version }}"
          distribution: "microsoft"
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        run: ./gradlew test